### ISSUE TITLE
[Question] Event Dispatcher in existing shlink docker

### ISSUE THREAD

**Issue by D-Visigo** [shlinkio/shlink-event-dispatcher#6]
Hello and thank you for building this great feature :-)

Is this just a workspace for you to test in? or is it 'live'?

Should I / Could I add this to an existing Shlink docker instance by following the installation instructions, or should I go about it another way? Will this be implemented in the standard/main docker builds or will it always remain "separate"

Thank you in advance for any answers you may have :-)

**Comment by acelaya** [comment]
Hey!

This is just some code split from shlink's main repo. It was part of the project in v1.18.0, so you don't have to do anything to get this working 

In later versions, shlink requires this as an external library and keeps making use of it.

So you don't have to worry 🙂
